### ISSUE TITLE
Error when lunch automator.py

### ISSUE THREAD

**Issue by Jbeuw** [sxpert/myhomepy#3]
Hello 

I want to try your code but I got this error :

> ./automator.py
2024-02-28 20:56:16 [DEVS] Initializing device database
DEBUG:asyncio:Using selector: EpollSelector
{'address': '192.168.0.1', 'port': 8080, 'session_key': 'TjyrR4L3By-uW5WS4tUnA='}
sessions setup
jinja2 setup
routes setup
Traceback (most recent call last):
  File "/home/thomas/myhomepy-master/./automator.py", line 68, in <module>
    a.run()
  File "/home/thomas/myhomepy-master/./automator.py", line 43, in run
    self.config.run()
  File "/home/thomas/myhomepy-master/config/config.py", line 158, in run
    self.systems.run()
  File "/home/thomas/myhomepy-master/config/systems.py", line 46, in run
    s.run()
  File "/home/thomas/myhomepy-master/config/system.py", line 186, in run
    self.gateway.setup_async()
  File "/home/thomas/myhomepy-master/config/gateway.py", line 157, in setup_async
    self.send_queue = asyncio.Queue(loop=self.loop)
  File "/usr/lib/python3.10/asyncio/queues.py", line 34, in __init__
    super().__init__(loop=loop)
  File "/usr/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

Can you help me ?

**Comment by sxpert** [comment]
there were major modifications to the asyncio stuff in recent python, the whole project won't work anymore as-is.
a rewrite is in the works (and has moved to my own gitlab instance)

**Comment by Jbeuw** [comment]
Ok thank you for this answer. Can you give me a link to your gitlab instance ? I want to follow this very interesting project.

**Comment by sxpert** [comment]
sure.
https://gitlab.sxpert.org/web-applications/myhomepy

**Comment by Jbeuw** [comment]
Thank you.

I'm new to GitHub or GitLab it is possible to help you ? I don't have skills in Python but I got a house with a MyHome Automation installation maybe I can test your work? I'm French BTW, I see you live in Grenoble.

**Comment by sxpert** [comment]
sure can. 
Am currently working on re-doing the asyncio core that connects to the F454 gateway.
Also, I'm looking into re-architecting the thing, which was kind of a mess.

**Comment by Jbeuw** [comment]
Cool, where do you prefer to talk about this ? Here ? on you GitLab ?

**Comment by sxpert** [comment]
my gitlab has the latest stuff, with more docs. this repo is considered dormant at this point (trying to wane myself off cloud services)

**Comment by Jbeuw** [comment]
Ok, but I don't find where to post to you messages on your GitLab instance.

**Comment by sxpert** [comment]
you should be able to create an issue there https://gitlab.sxpert.org/web-applications/myhomepy/-/issues

**Comment by Jbeuw** [comment]
It ask me to log in but don't propose to sign in.

**Comment by sxpert** [comment]
> It ask me to log in but don't propose to sign in.

oh, I had that deactivated... should work now ;)
